# Generated by Django 5.1.4 on 2025-01-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_scraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="map_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
