# Generated by Django 5.1.4 on 2025-01-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_scraper", "0002_apartment_map_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crime_name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("relevant_to_party_map", models.BooleanField(default=False)),
            ],
        ),
    ]
