# Generated by Django 5.1.4 on 2025-01-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_scraper", "0003_crime"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="overall_satisfaction",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="review_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
